// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKXoq5v23Q3YTnlf1KMOiWpXjm5e0MnA',
    appId: '1:930861583274:web:54668fdea32ec06989f9d3',
    messagingSenderId: '930861583274',
    projectId: 'notes-firebase-aa222',
    authDomain: 'notes-firebase-aa222.firebaseapp.com',
    storageBucket: 'notes-firebase-aa222.appspot.com',
    measurementId: 'G-G9E1TG05NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvUTVoBSyxAbiVvwAa8CIlZKfZwMjBGs',
    appId: '1:930861583274:android:ca687b6573d3160c89f9d3',
    messagingSenderId: '930861583274',
    projectId: 'notes-firebase-aa222',
    storageBucket: 'notes-firebase-aa222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo42HFbAKZ4-YR-J2PFIufBXdz7yC6PN8',
    appId: '1:930861583274:ios:88cbc91a1e94b5b189f9d3',
    messagingSenderId: '930861583274',
    projectId: 'notes-firebase-aa222',
    storageBucket: 'notes-firebase-aa222.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo42HFbAKZ4-YR-J2PFIufBXdz7yC6PN8',
    appId: '1:930861583274:ios:88cbc91a1e94b5b189f9d3',
    messagingSenderId: '930861583274',
    projectId: 'notes-firebase-aa222',
    storageBucket: 'notes-firebase-aa222.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKXoq5v23Q3YTnlf1KMOiWpXjm5e0MnA',
    appId: '1:930861583274:web:1f68a06e2fcd0e9b89f9d3',
    messagingSenderId: '930861583274',
    projectId: 'notes-firebase-aa222',
    authDomain: 'notes-firebase-aa222.firebaseapp.com',
    storageBucket: 'notes-firebase-aa222.appspot.com',
    measurementId: 'G-EGR186BY20',
  );
}
